apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-v3
  namespace: default
spec:
  selector:
    matchLabels:
      app: nginx
      version: v3
  replicas: 3
  template:
    metadata:
      labels:
          app: nginx
          version: v3
    spec:
      containers:
        - name: nginx
          image: nginx:1.17.6
          ports:
           - containerPort: 80
          volumeMounts:
           - name: timezone
             mountPath: /etc/localtime
           - name: nginx-conf
             mountPath: /etc/nginx/conf.d/default.conf
             subPath: default.conf
             readOnly: true
           - name: nginx-server-certs
             mountPath: /etc/nginx/nginx-server-certs
             readOnly: true
      volumes:
        - name: timezone
          hostPath:
             path: /usr/share/zoneinfo/Asia/Shanghai
        - name: nginx-conf
          configMap:
            name: nginx-configmap
        - name: nginx-server-certs
          secret:
            secretName: nginx-server-certs
